version: '3'

services:
  mirrors:
    image: nginx:1.19.2-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
      - ./logs:/var/log/nginx
